app:
  addr: ":7777"
  image_path: "/home/kkkstra/Pictures/cqhttp/"
cqhttp:
  addr: "http://localhost:5700"
postgresql:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "204406"
  dbname: "fatsharkbot"
bot:
  qq: "2494611478"
  name: "肥肥鲨bot"